---
version: "3"
name: "example"

services:
  nginx:
    image: nginx:stable-alpine
    labels:
      - expose.vhost=example.wyga.site
    networks:
      wyga-site:
        priority: 100
      default:
        priority: 500

networks:
  wyga-site:
    external: true
