---
version: "3"
name: "wyga-site"

services:
  wyga-site-gateway:
    image: wyga/wyga-site
    logging:
      options:
        max-file: "10"
        max-size: "25m"
        compress: "true"
    container_name: wyga-site-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - gateway
    ports:
      - ${WYGA_SITE_HTTPS_PORT:-443}:443
      - ${WYGA_SITE_HTTP_PORT:-80}:80
    environment:
      WYGA_SITE_DASHBOARD: "${WYGA_SITE_DASHBOARD:-traefik.wyga.site}"
      WYGA_SITE_LOGLEVEL: "${WYGA_SITE_LOGLEVEL:-error}"
      WYGA_SITE_ACCESSLOG: "${WYGA_SITE_ACCESSLOG:-true}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  gateway:
    external: true
